var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/crypto/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00tp3z_._.js")
R.c("server/chunks/ssr/09q._next_dist_0juq9c.._.js")
R.c("server/chunks/ssr/09q._next_dist_esm_build_templates_app-page_0.hl983.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p-k~_n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ver2ty._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jmnaer._.js")
R.c("server/chunks/ssr/_0ggslm0._.js")
R.c("server/chunks/ssr/src_lib_utils_ts_0cn8qfr._.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_08baqiv._.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_builtin_unauthorized_0ohxx4-.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_builtin_global-error_0g4bv3z.js")
R.c("server/chunks/ssr/src_0i5ppc.._.js")
R.c("server/chunks/ssr/src_0ywp4do._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_crypto_page_actions_0cojzdv.js")
R.m(89987)
module.exports=R.m(89987).exports
