-- Authoritative customer account numbers and lifecycle. Applied migrations remain immutable.
ALTER TABLE accounts DROP CONSTRAINT IF EXISTS customer_fiat_internal_number_required;
DROP TRIGGER IF EXISTS accounts_assign_internal_number ON accounts;
DROP FUNCTION IF EXISTS assign_internal_account_number();
DROP INDEX IF EXISTS accounts_user_currency_env;

ALTER TABLE accounts ADD COLUMN closed_at timestamptz;
ALTER TABLE accounts ADD CONSTRAINT accounts_customer_status
  CHECK (account_owner_type <> 'CUSTOMER' OR status IN ('ACTIVE','CLOSED','RESTRICTED'));

CREATE OR REPLACE FUNCTION generate_trinex_account_number() RETURNS text
LANGUAGE plpgsql VOLATILE AS $$
DECLARE candidate text;
BEGIN
  LOOP
    -- gen_random_uuid() uses PostgreSQL's cryptographic random source and is
    -- available in the Netlify Database runtime.
    candidate := translate(
      substr(replace(gen_random_uuid()::text, '-', ''), 1, 12),
      'abcdef',
      '012345'
    );
    EXIT WHEN NOT EXISTS (SELECT 1 FROM accounts WHERE internal_account_number=candidate);
  END LOOP;
  RETURN candidate;
END $$;

UPDATE accounts SET internal_account_number=generate_trinex_account_number()
WHERE account_owner_type='CUSTOMER' AND currency IN ('USD','EUR','GBP');

ALTER TABLE accounts ADD CONSTRAINT customer_fiat_account_number_format CHECK (
  account_owner_type <> 'CUSTOMER' OR currency NOT IN ('USD','EUR','GBP') OR
  (internal_account_number IS NOT NULL AND internal_account_number ~ '^[0-9]{12}$')
);

CREATE OR REPLACE FUNCTION assign_trinex_account_number() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.account_owner_type='CUSTOMER' AND NEW.currency IN ('USD','EUR','GBP') THEN
    IF NEW.internal_account_number IS NOT NULL THEN
      RAISE EXCEPTION 'Customer account numbers are generated by the server';
    END IF;
    NEW.internal_account_number := generate_trinex_account_number();
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER accounts_assign_trinex_number BEFORE INSERT ON accounts
FOR EACH ROW EXECUTE FUNCTION assign_trinex_account_number();

CREATE TABLE account_lookup_attempts (
  id bigserial PRIMARY KEY,
  customer_id uuid NOT NULL REFERENCES users(id),
  attempted_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX account_lookup_attempts_customer_time_idx ON account_lookup_attempts(customer_id,attempted_at DESC);

CREATE INDEX accounts_user_active_idx ON accounts(user_id,status,currency,created_at)
WHERE account_owner_type='CUSTOMER' AND environment='PRODUCTION';

-- A ledger account belongs to one customer account, including when currencies repeat.
CREATE OR REPLACE FUNCTION validate_account_currency_chain() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE account_currency text; resolved_account_id uuid; resolved_status transfer_status;
BEGIN
  SELECT a.currency, a.id, t.status INTO account_currency, resolved_account_id, resolved_status
  FROM ledger_accounts la JOIN accounts a ON a.id=la.account_id
  JOIN transactions t ON t.id=NEW.transaction_id
  WHERE la.id=NEW.ledger_account_id;
  IF account_currency IS NULL OR NEW.currency<>account_currency THEN RAISE EXCEPTION 'Ledger entry currency must match its customer account'; END IF;
  NEW.account_id := resolved_account_id;
  NEW.status := resolved_status;
  RETURN NEW;
END $$;
