var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0r1oi2~._.js")
R.c("server/chunks/ssr/09q._next_dist_esm_build_templates_app-page_0w3q04j.js")
R.c("server/chunks/ssr/09q._next_dist_0juq9c.._.js")
R.c("server/chunks/ssr/_02qu3me._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p-k~_n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ver2ty._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jmnaer._.js")
R.c("server/chunks/ssr/_0ggslm0._.js")
R.c("server/chunks/ssr/src_lib_utils_ts_0cn8qfr._.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_08baqiv._.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_builtin_unauthorized_0ohxx4-.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_builtin_global-error_0g4bv3z.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_09-gtaw.js")
R.m(32648)
module.exports=R.m(32648).exports
