"use client"

import Link from "next/link"
import { Eye, EyeOff, Landmark, LoaderCircle } from "lucide-react"
import { useState } from "react"

export function AuthForm({mode="sign-in",admin=false}:{mode?:"sign-in"|"sign-up";admin?:boolean}){
 const signup=mode==="sign-up",[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("")
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),name=String(data.get("name")||""),email=String(data.get("email")||""),password=String(data.get("password")||""),confirm=String(data.get("confirm")||"");setNotice("");if(signup&&name.trim().length<2){setError("Enter your full name.");return}if(!/^\S+@\S+\.\S+$/.test(email)){setError("Enter a valid email address.");return}if(password.length<8||!/[A-Z]/.test(password)||!/[0-9]/.test(password)){setError("Use at least 8 characters with one uppercase letter and one number.");return}if(signup&&password!==confirm){setError("Passwords do not match.");return}if(signup&&!data.get("terms")){setError("Accept the development terms to continue.");return}setError("");setLoading(true);setTimeout(()=>{setLoading(false);setNotice("Authentication is currently in development. Validation passed, but no account or session was created and no password was stored.")},650)}
 return <div className="auth"><section className="auth-art"><Link className="brand" href="/"><span className="mark"><span>T</span></span><span><strong>TRINEX BUSINESSPAY</strong><small>ONE PLATFORM. GLOBAL FINANCE.</small></span></Link><div className="auth-copy"><span className="eyebrow">DEVELOPMENT MODE</span><h1>One platform.<br/>Global finance.</h1><p>Explore the interface in a clearly isolated sandbox. No real customer or financial services are connected.</p></div><small>TRINEX BUSINESSPAY · DEMO / SANDBOX</small></section><main className="auth-panel"><div className="auth-box"><Landmark color="var(--gold)"/><span className="eyebrow">{admin?"Separate administrator access":"Customer access"}</span><h2>{admin?"Admin sign in":signup?"Create your account":"Welcome back"}</h2><div className="notice" style={{margin:"20px 0"}}>Authentication is currently in development. Credentials are validated in the browser and never stored.</div><form className="form" onSubmit={submit} noValidate>{signup&&<div className="field"><label htmlFor="name">Full name</label><input id="name" name="name" autoComplete="name"/></div>}<div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" autoComplete="email"/></div><div className="field"><label htmlFor="password">Password</label><div className="password-wrap"><input id="password" name="password" type={show?"text":"password"} autoComplete={signup?"new-password":"current-password"}/><button type="button" className="icon-btn" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div>{signup&&<><div className="field"><label htmlFor="confirm">Confirm password</label><input id="confirm" name="confirm" type={show?"text":"password"} autoComplete="new-password"/></div><label className="check-row"><input name="terms" type="checkbox"/>I agree to the development sandbox terms</label></>}{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice success" role="status">{notice}</div>}<button className="btn" disabled={loading}>{loading?<><LoaderCircle className="spin" size={17}/>Validating…</>:signup?"Validate signup":"Validate sign in"}</button></form>{!admin&&<p className="muted">{signup?"Already have an account? ":"Need an account? "}<Link href={signup?"/login":"/signup"}>{signup?"Sign in":"Sign up"}</Link></p>}<p><Link href={admin?"/admin":"/dashboard"}>{admin?"Return to admin demo":"Explore customer sandbox"}</Link></p></div></main></div>
}
