"use client"

import Link from "next/link"
import { Eye, EyeOff, Landmark, LoaderCircle } from "lucide-react"
import { useState } from "react"

export function AuthForm({mode="sign-in",admin=false}:{mode?:"sign-in"|"sign-up";admin?:boolean}){
 const signup=mode==="sign-up",[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("")
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),email=String(data.get("email")||""),password=String(data.get("password")||"");setNotice("");if(!/^\S+@\S+\.\S+$/.test(email)){setError("Enter a valid email address.");return}if(password.length<8){setError("Password must contain at least 8 characters.");return}setError("");setLoading(true);setTimeout(()=>{setLoading(false);setNotice(`${admin?"Admin authentication":"Authentication"} is not connected. No credentials were stored and no session was created.`)},500)}
 return <div className="auth"><section className="auth-art"><Link className="brand" href="/"><span className="mark"><span>T</span></span><span><strong>TRINEX BUSINESSPAY</strong><small>ONE PLATFORM. GLOBAL FINANCE.</small></span></Link><div className="auth-copy"><span className="eyebrow">Built for business without borders</span><h1>One platform.<br/>Global finance.</h1><p>Authentication remains visibly disconnected until a production identity provider is integrated.</p></div><small>TRINEX BUSINESSPAY · SECURE ACCESS</small></section><main className="auth-panel"><div className="auth-box"><Landmark color="var(--gold)"/><span className="eyebrow">{admin?"Separate administrator access":"Customer access"}</span><h2>{admin?"Admin sign in":signup?"Create your account":"Welcome back"}</h2><p style={{color:"var(--muted)"}}>{admin?"Administrator and customer authentication are kept separate.":signup?"Enter your details to check account requirements.":"Enter your details to check service availability."}</p><div className="notice" style={{margin:"20px 0"}}>Not connected — submitting this form does not authenticate or create an account.</div><form className="form" onSubmit={submit} noValidate>{signup&&<div className="field"><label htmlFor="name">Full name</label><input id="name" name="name" required minLength={2}/></div>}<div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" autoComplete="email" required/></div><div className="field"><label htmlFor="password">Password</label><div style={{position:"relative"}}><input id="password" name="password" type={show?"text":"password"} autoComplete={signup?"new-password":"current-password"} required minLength={8}/><button type="button" className="icon-btn" style={{position:"absolute",right:2,top:1}} onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div>{signup&&<label style={{display:"flex",gap:10,fontSize:13}}><input type="checkbox" required/>I agree to the terms and privacy policy</label>}{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}<button className="btn" disabled={loading}>{loading?<><LoaderCircle size={17}/>Checking connection…</>:signup?"Check account availability":"Check sign-in availability"}</button></form>{!admin&&<p style={{fontSize:13,color:"var(--muted)"}}>{signup?"Already have an account? ":"Need an account? "}<Link href={signup?"/sign-in":"/sign-up"}>{signup?"Sign in":"Sign up"}</Link></p>}<p><Link href="/dashboard">Return to dashboard</Link></p></div></main></div>
}
