"use client"

import { useRouter } from "next/navigation"
import { useMemo, useState } from "react"
import { ArrowRight, CreditCard, Send, TrendingUp, WalletCards, X, SlidersHorizontal, Search } from "lucide-react"

const financial=new Set(["Accounts","Transfers","Cards","Crypto","Investments","Payments","Budgets"])
const descriptions:Record<string,string>={
 Dashboard:"A clear operational view of your global finance workspace.",Accounts:"Connect and manage business accounts across currencies.",Transactions:"Search and review ledger activity from connected providers.",Transfers:"Prepare domestic and international money movements.",Cards:"Control physical and virtual business cards.",Crypto:"Review digital asset services and custody connectivity.",Investments:"Manage investment instructions and portfolio access.",Payments:"Create and track supplier and business payments.",Budgets:"Set frontend planning limits and category preferences.",Notifications:"Choose how operational notices reach you.",Support:"Contact the TRINEX support team.",Security:"Manage local interface security preferences.",Settings:"Update workspace preferences stored for this session."
}

export function FeaturePage({title}:{title:string}){
 const [modal,setModal]=useState(false),[tab,setTab]=useState("Overview"),[query,setQuery]=useState(""),[filters,setFilters]=useState(false),[message,setMessage]=useState("")
 if(title==="Dashboard") return <Dashboard/>
 if(title==="Transactions") return <><Head title={title}/><section className="card full"><div className="tabs">{["All","Incoming","Outgoing"].map(x=><button className={`tab ${tab===x?"active":""}`} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="toolbar" style={{marginTop:16}}><input id="transaction-search" autoFocus className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by reference, provider, or amount" aria-label="Search transactions"/><button className="btn secondary" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={17}/>Filter</button></div>{filters&&<div className="notice" style={{marginBottom:16}}>No connected transaction source is available to filter. Connect a backend ledger to display results.</div>}<div className="empty"><Search/><h3>No transactions available</h3><p>{query?`No connected records match “${query}”.`:"A connected ledger is required before transaction activity can appear."}</p></div></section></>
 if(title==="Support") return <><Head title={title}/><LocalForm/></>
 if(title==="Settings"||title==="Security"||title==="Notifications") return <><Head title={title}/><Preferences title={title}/></>
 const tabs=title==="Crypto"?["Overview","Trade","Custody"]:title==="Investments"?["Portfolio","Markets","Orders"]:["Overview","Activity","Details"]
 return <><Head title={title}/><div className="tabs">{tabs.map(x=><button key={x} className={`tab ${tab===x?"active":""}`} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="grid" style={{marginTop:18}}><section className="card wide"><h2>{tab}</h2><p>This workspace is ready for provider data, but no financial backend is connected. No balances, transactions, or confirmations are shown.</p><div className="notice">Backend connection required</div></section><button className="card action-card" onClick={()=>setModal(true)}><Send/><h3>{title==="Accounts"?"Connect account":title==="Cards"?"Request a card":`Start ${title.toLowerCase()} action`}</h3><p>Open the guided frontend form.</p><ArrowRight size={18}/></button></div>{modal&&<ActionModal title={title} close={()=>{setModal(false);setMessage("")}} message={message} setMessage={setMessage}/>}</>
}

function Head({title}:{title:string}){return <div className="page-head"><div><span className="eyebrow">TRINEX BUSINESSPAY</span><h1>{title}</h1><p>{descriptions[title]}</p></div>{financial.has(title)&&<span className="status"><span className="dot"/>Not connected</span>}</div>}

function Dashboard(){const router=useRouter();return <><Head title="Dashboard"/><div className="notice" style={{marginBottom:18}}>Financial data is hidden until a real ledger and account provider are connected. No sample balances are being presented as real.</div><div className="grid">{[["Accounts","/accounts",WalletCards],["Send money","/transfers",Send],["Card controls","/cards",CreditCard],["Investments","/investments",TrendingUp]].map(([label,path,Icon])=><button key={String(path)} className="card action-card" onClick={()=>router.push(String(path))}><Icon size={25}/><h3>{String(label)}</h3><p>Open workspace</p><ArrowRight size={18}/></button>)}</div></>}

function ActionModal({title,close,message,setMessage}:{title:string;close:()=>void;message:string;setMessage:(v:string)=>void}){const [value,setValue]=useState(""),[loading,setLoading]=useState(false);function submit(e:React.FormEvent){e.preventDefault();if(!value.trim()){setMessage("Complete the required field.");return}setLoading(true);setTimeout(()=>{setLoading(false);setMessage("Backend connection required. Nothing was submitted or processed.")},450)}return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-label={`${title} action`}><div className="modal-head"><div><span className="eyebrow">Guided action</span><h2>{title}</h2></div><button className="icon-btn" onClick={close} aria-label="Close"><X/></button></div><form className="form" onSubmit={submit}><div className="field"><label htmlFor="action-value">{title==="Accounts"?"Institution or provider":"Amount or instruction"}</label><input id="action-value" value={value} onChange={e=>setValue(e.target.value)} required placeholder="Required"/></div>{message&&<div className="notice">{message}</div>}<div className="toolbar"><button type="button" className="btn ghost" onClick={close}>Cancel</button><button className="btn" disabled={loading}>{loading?"Checking connection…":"Continue"}</button></div></form></div></div>}

function Preferences({title}:{title:string}){const [enabled,setEnabled]=useState(false),[saved,setSaved]=useState(false);return <section className="card full"><h2>{title} preferences</h2><p>These controls change frontend state only. Account-level persistence requires authentication and backend services.</p><label style={{display:"flex",alignItems:"center",gap:12,minHeight:48}}><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);setSaved(false)}}/>Enable {title.toLowerCase()} preference</label><button className="btn" onClick={()=>setSaved(true)}>Save preference</button>{saved&&<div className="notice success" style={{marginTop:14}}>Saved for this page session. Backend persistence is not connected.</div>}</section>}

function LocalForm(){const [subject,setSubject]=useState(""),[body,setBody]=useState(""),[error,setError]=useState(""),[sent,setSent]=useState(false);const valid=useMemo(()=>subject.trim().length>=3&&body.trim().length>=10,[subject,body]);function submit(e:React.FormEvent){e.preventDefault();if(!valid){setError("Enter a subject of at least 3 characters and a message of at least 10 characters.");return}setError("");setSent(true)}return <section className="card full"><form className="form" onSubmit={submit}><div className="field"><label htmlFor="subject">Subject</label><input id="subject" value={subject} onChange={e=>setSubject(e.target.value)} required/></div><div className="field"><label htmlFor="message">Message</label><textarea id="message" value={body} onChange={e=>setBody(e.target.value)} required/></div>{error&&<div className="error">{error}</div>}{sent&&<div className="notice">Support delivery is not connected. Your message was not sent; you can copy it before leaving this page.</div>}<button className="btn">Check message</button></form></section>}
