var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/transfers/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__105-fpn._.js")
R.c("server/chunks/ssr/09q._next_dist_0juq9c.._.js")
R.c("server/chunks/ssr/09q._next_dist_esm_build_templates_app-page_0p43vzx.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p-k~_n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ver2ty._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jmnaer._.js")
R.c("server/chunks/ssr/_0ggslm0._.js")
R.c("server/chunks/ssr/src_lib_utils_ts_0cn8qfr._.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_08baqiv._.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_builtin_unauthorized_0ohxx4-.js")
R.c("server/chunks/ssr/09q._next_dist_client_components_builtin_global-error_0g4bv3z.js")
R.c("server/chunks/ssr/src_0i5ppc.._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_transfers_page_actions_0otra.1.js")
R.m(2831)
module.exports=R.m(2831).exports
